import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Header from "../components/Header";
import Banner from "../components/Banner";
import ItemDesc from "../components/ItemDesc";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>bejamas store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="components">
        <Navbar />
        <Header />
        <Banner />
        <ItemDesc />
      </div>
    </div>
  );
}
